version: '3.8'
services:
  bekie:
    container_name: bekie
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
